circuitsacul/Starboard-4

- sqlx-data.json
- src/cache/cache.rs
- src/core/starboard/config.rs
- src/core/starboard/reaction_events.rs
- src/database/models/guild.rs
- src/database/models/starboard_override.rs
- src/interactions/commands/chat/starboard/create.rs
- src/interactions/commands/chat/starboard/delete.rs
- src/interactions/commands/chat/starboard/edit/requirements.rs
> skip handling reactions for non-vote emojis

- src/interactions/commands/chat/ping.rs
- src/interactions/commands/handle.rs
Unknown is spelled better (probably)
> typo: unkown --> unknown

- Cargo.toml
- src/client/bot.rs
- src/core/embedder/handle.rs
- src/events/mod.rs
- src/utils/system_content.rs
> update twilight libraries

- sqlx-data.json
- src/database/models/starboard.rs
- src/database/models/starboard_override.rs
- src/database/validation/cooldown.rs
- src/database/validation/mod.rs
- src/interactions/autocomplete/handle.rs
- src/interactions/commands/chat/overrides/edit/behavior.rs
- src/interactions/commands/chat/overrides/edit/embed.rs
- src/interactions/commands/chat/overrides/edit/mod.rs
- src/interactions/commands/chat/overrides/edit/requirements.rs
- src/interactions/commands/chat/overrides/edit/reset.rs
- src/interactions/commands/chat/overrides/edit/style.rs
- src/interactions/commands/chat/overrides/mod.rs
Attempted to reduce code duplication as much as I could...
> Add override setting edit commands

- src/core/starboard/handle.rs
> autoreact upvote/downvote emojis

- src/cache/cache.rs
- src/cache/events/guild.rs
- src/cache/events/member.rs
- src/cache/models/guild.rs
- src/cache/models/member.rs
- src/cache/models/mod.rs
- src/core/embedder/builder.rs
- src/core/embedder/handle.rs
- src/core/starboard/handle.rs
> cache member events, use server profile

- src/cache/events/member.rs
- src/core/starboard/handle.rs
- src/core/starboard/link_events.rs
- src/core/starboard/mod.rs
- src/core/starboard/reaction_events.rs
- src/events/mod.rs
> trigger an update for message edits/deletes

- sqlx-data.json
- src/cache/cache_struct.rs
- src/core/embedder/builder.rs
- src/core/embedder/handle.rs
- src/core/starboard/handle.rs
- src/core/starboard/mod.rs
- src/core/starboard/webhooks.rs
- src/database/models/starboard.rs
- src/interactions/commands/chat/random.rs
> Webhook Support

- src/core/posroles.rs
allows for proper posrole removal
> fetch twice the leaderboard needed

- src/core/starboard/handle.rs
- src/core/starboard/link_events.rs
- src/core/starboard/reaction_events.rs
- src/events/mod.rs
- src/interactions/commands/chat/utils/force.rs
- src/interactions/commands/chat/utils/freeze.rs
- src/interactions/commands/chat/utils/refresh.rs
- src/interactions/commands/chat/utils/trash.rs
- src/interactions/commands/chat/utils/unforce.rs
> update starboards concurrently

- migrations/20230121060809_no_override_xp_multiplier.sql
- src/database/helpers/settings/overrides.rs
- src/database/models/starboard_override_values.rs
- src/interactions/commands/chat/overrides/edit/behavior.rs
- src/interactions/commands/format_settings.rs
> remove xp-multiplier from overrides

- src/client/cooldowns.rs
- src/client/locks.rs
- src/constants.rs
- src/core/emoji.rs
- src/core/starboard/mod.rs
- src/core/starboard/recount.rs
- src/interactions/commands/chat/utils/mod.rs
- src/interactions/commands/chat/utils/recount.rs
> add recount command

- src/interactions/commands/chat/utils/info.rs
> show point count in /utils info

- src/core/embedder/builder.rs
> remove *file only* notice from empty embeds

- src/core/premium/redeem.rs
- src/interactions/commands/chat/autostar/delete.rs
- src/interactions/commands/chat/starboard/delete.rs
> update premium locks in more cases

- Cargo.lock
- Cargo.toml
- src/cache/cache_struct.rs
- src/constants.rs
- src/core/starboard/handle.rs
- src/core/starboard/link_events.rs
> use an LRU cache for deletions

- src/utils/message_link.rs
> make message link parsing more flexible

- src/core/embedder/attachment_handle.rs
- src/core/embedder/builder.rs
> Attachment list fixes

- src/interactions/commands/chat/moststarred.rs
> add back button to moststarred command

- src/constants.rs
> lower edit cooldown back to 2/10s

- src/core/embedder/builder.rs
- src/interactions/commands/chat/moststarred.rs
- src/interactions/commands/chat/random.rs
> add go to message button for random

- src/interactions/commands/chat/permroles/edit_starboard.rs
- src/utils/pg_error.rs
> fix fk violation for /permroles edit-starboard

- src/utils/system_content.rs
> add missing message types for system content

- src/cache/events/message.rs
- src/cache/models/message.rs
- src/core/embedder/builder.rs
> Author field fixes

- src/core/emoji.rs
> don't break for custom emojis with numbers in name

- src/cache/cache_struct.rs
- src/core/emoji.rs
- src/core/starboard/config.rs
- src/core/starboard/reaction_events.rs
- src/core/starboard/recount.rs
- src/database/models/starboard_override.rs
- src/database/models/starboard_settings.rs
I hate unicode, especially emojis and V16. That is all.
> Fix some emojis that actually require V16

- src/core/embedder/builder.rs
> always show files in the attachments list

- src/core/emoji.rs
- src/interactions/commands/chat/autostar/edit.rs
- src/interactions/commands/chat/overrides/edit/requirements.rs
- src/interactions/commands/chat/overrides/edit/style.rs
- src/interactions/commands/chat/starboard/edit/requirements.rs
- src/interactions/commands/chat/starboard/edit/style.rs
> use regex to parse emojis without spaces

- src/core/filters.rs
> forum starter messages belong to forum, not post

- src/core/embedder/builder.rs
Reverts CircuitSacul/Starboard-4#287
> Revert "always show files in the attachments list"

- src/core/embedder/builder.rs
- src/core/embedder/handle.rs
- src/interactions/commands/chat/moststarred.rs
- src/interactions/commands/chat/random.rs
Redoes https://github.com/CircuitSacul/Starboard-4/pull/287
Closes https://github.com/CircuitSacul/Starboard-4/issues/286
> Always show file names in attachments list

- src/core/autostar.rs
- src/interactions/commands/chat/help.rs
- src/interactions/commands/chat/utils/mod.rs
- src/owner/commands/sql.rs
> fix markdown lists

- src/cache/cache_struct.rs
- src/core/embedder/handle.rs
- src/core/starboard/webhooks.rs
- src/interactions/commands/chat/overrides/edit/style.rs
- src/interactions/commands/chat/starboard/edit/style.rs
> create webhooks as soon as the setting is enabled

- src/core/embedder/attachment_handle.rs
- src/core/embedder/builder.rs
- src/core/embedder/image_only_embed.rs
- src/core/embedder/parser.rs
> Embedder improvements

- Cargo.lock
- Cargo.toml
- src/core/emoji.rs
> fix: update emojis dep, fix V16 inside glued emojis
